spring:
  profiles:
    active: avijit
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true

security:
  jwt:
    secret: mrrobotsecuritykey
    timeout: 86400
post:
  rank:
    defaultPoint: 5.0
  defaultLimit: 2
  topic:
    defaultHotLimit: 2
  defaultPostPoint: 5
  defaultCommentPoint: 2

server:
  port: 8999
  servlet:
    context-path: /overflow